name = "MyLeanRepo"
version = "0.1.0"
defaultTargets = ["MyLeanRepo"]

[[require]]
name = "mathlib"
path = ".lake/packages/mathlib"

[[lean_lib]]
name = "MyLeanRepo"
moreLeanArgs = ["-DautoImplicit=false", "-Dlinter.all=false"]

[[lean_lib]]
name = "Kakeya"
moreLeanArgs = ["-DrelaxedAutoImplicit=false", "-Dlinter.all=false", "-DmaxSynthPendingDepth=3"]

[[lean_lib]]
name = "FinalCheck"
moreLeanArgs = ["-DrelaxedAutoImplicit=false", "-Dlinter.all=false", "-DmaxSynthPendingDepth=3"]

[[lean_lib]]
name = "Comparator"
moreLeanArgs = ["-DrelaxedAutoImplicit=false", "-Dlinter.all=false"]
