import MyLeanRepo.Kakeya.Streamlined.MainLemmaTwo.AssignedPhysicalExactActualMassCardinalityUpperLedger
import MyLeanRepo.Diagnostics.NumObjs

open Kakeya.Streamlined.GenealogyTransport

run_cmd MyLeanRepo.Diagnostics.reportNumObjs #[
  `Kakeya.Streamlined.GenealogyTransport.AssignedPhysicalExactActualMassScheduledStepPackage.processedParent_enncard_le_occurrence,
  `Kakeya.Streamlined.GenealogyTransport.AssignedPhysicalExactActualMassScheduledStepPackage.product_le_two_mul_of_eq_of_le_of_le,
  `Kakeya.Streamlined.GenealogyTransport.AssignedPhysicalExactActualMassScheduledStepPackage.finalChildren_raw_exactPartition_upper_proof,
  `Kakeya.Streamlined.GenealogyTransport.AssignedPhysicalExactActualMassScheduledStepPackage.finalChildren_exactPartition_upper_proof,
  `Kakeya.Streamlined.GenealogyTransport.AssignedPhysicalExactActualMassScheduledStepPackage.finalChildren_exactPartition_upper,
  `Kakeya.Streamlined.GenealogyTransport.FreshKatzTaoAssignedPhysicalExactActualMassReachable.factorProduct_le_two_of_factors_eq,
  `Kakeya.Streamlined.GenealogyTransport.FreshKatzTaoAssignedPhysicalExactActualMassReachable.activeRefinement_product_le_previous,
  `Kakeya.Streamlined.GenealogyTransport.FreshKatzTaoAssignedPhysicalExactActualMassReachable.canonicalMassProfile_product_le_two_previous,
  `Kakeya.Streamlined.GenealogyTransport.FreshKatzTaoAssignedPhysicalExactActualMassReachable.physicalExactActualMass_product_le_two_previous,
  `Kakeya.Streamlined.GenealogyTransport.FreshKatzTaoAssignedPhysicalExactActualMassReachable.cardinalityProduct_two_step_transition,
  `Kakeya.Streamlined.GenealogyTransport.FreshKatzTaoAssignedPhysicalExactActualMassReachable.cardinalityProduct_le_two_pow_proof,
  `Kakeya.Streamlined.GenealogyTransport.FreshKatzTaoAssignedPhysicalExactActualMassReachable.cardinalityProduct_le_two_pow,
  `Kakeya.Streamlined.GenealogyTransport.FreshKatzTaoAssignedPhysicalExactActualMassReachable.balancedPotentialProduct_le_two_pow,
  `Kakeya.Streamlined.GenealogyTransport.FreshKatzTaoAssignedPhysicalExactActualMassReachable.balancedPotentialProduct_le_depth_coefficient,
  `Kakeya.Streamlined.GenealogyTransport.FreshKatzTaoAssignedPhysicalExactActualMassReachable.exists_balancedPotentialProduct_cutoff
]

#print axioms Kakeya.Streamlined.GenealogyTransport.AssignedPhysicalExactActualMassScheduledStepPackage.finalChildren_raw_exactPartition_upper_proof
#print axioms Kakeya.Streamlined.GenealogyTransport.AssignedPhysicalExactActualMassScheduledStepPackage.finalChildren_exactPartition_upper_proof
#print axioms Kakeya.Streamlined.GenealogyTransport.FreshKatzTaoAssignedPhysicalExactActualMassReachable.activeRefinement_product_le_previous
#print axioms Kakeya.Streamlined.GenealogyTransport.FreshKatzTaoAssignedPhysicalExactActualMassReachable.canonicalMassProfile_product_le_two_previous
#print axioms Kakeya.Streamlined.GenealogyTransport.FreshKatzTaoAssignedPhysicalExactActualMassReachable.physicalExactActualMass_product_le_two_previous
#print axioms Kakeya.Streamlined.GenealogyTransport.FreshKatzTaoAssignedPhysicalExactActualMassReachable.cardinalityProduct_two_step_transition
#print axioms Kakeya.Streamlined.GenealogyTransport.FreshKatzTaoAssignedPhysicalExactActualMassReachable.cardinalityProduct_le_two_pow_proof
#print axioms Kakeya.Streamlined.GenealogyTransport.FreshKatzTaoAssignedPhysicalExactActualMassReachable.balancedPotentialProduct_le_two_pow
