import MyLeanRepo.Kakeya.Streamlined.MainLemmaTwo.AssignedPhysicalActualMassScheduledStep
import MyLeanRepo.Diagnostics.NumObjs

run_cmd MyLeanRepo.Diagnostics.reportNumObjs #[
  `Kakeya.Streamlined.GenealogyTransport.assignedPhysicalActualMass_outerToSelected,
  `Kakeya.Streamlined.GenealogyTransport.assignedPhysicalActualMass_selectedToExact,
  `Kakeya.Streamlined.GenealogyTransport.assignedPhysicalActualMass_exactToScale,
  `Kakeya.Streamlined.GenealogyTransport.assignedPhysicalActualMass_outerGlobal,
  `Kakeya.Streamlined.GenealogyTransport.assignedPhysicalActualMass_outerRaw,
  `Kakeya.Streamlined.GenealogyTransport.assignedPhysicalActualMass_innerRaw,
  `Kakeya.Streamlined.GenealogyTransport.assigned_physical_actual_mass_scheduled_step_core,
  `Kakeya.Streamlined.GenealogyTransport.assigned_physical_actual_mass_scheduled_step,
  `Kakeya.Streamlined.GenealogyTransport.AssignedPhysicalActualMassScheduledStepPackage.assignedExactFamily_heq_directExactFamily,
  `Kakeya.Streamlined.GenealogyTransport.AssignedPhysicalActualMassScheduledStepPackage.assignedRegisteredScale_eq_directRegisteredScale,
  `Kakeya.Streamlined.GenealogyTransport.AssignedPhysicalActualMassScheduledStepPackage.nextWithAllCarriersPositive,
  `Kakeya.Streamlined.GenealogyTransport.AssignedPhysicalActualMassScheduledStepPackage.nextNode,
  `Kakeya.Streamlined.GenealogyTransport.AssignedPhysicalActualMassScheduledStepPackage.nextNode_allCarriersPositive,
  `Kakeya.Streamlined.GenealogyTransport.AssignedPhysicalActualMassScheduledStepPackage.toNext,
  `Kakeya.Streamlined.GenealogyTransport.AssignedPhysicalActualMassScheduledStepPackage.toNext_eq_nextWithAllCarriersPositive,
  `Kakeya.Streamlined.GenealogyTransport.AssignedPhysicalActualMassScheduledStepPackage.toNext_shadings_heq,
  `Kakeya.Streamlined.GenealogyTransport.AssignedPhysicalActualMassScheduledStepPackage.allCarriersPositive
]

#print axioms Kakeya.Streamlined.GenealogyTransport.assigned_physical_actual_mass_scheduled_step_core
#print axioms Kakeya.Streamlined.GenealogyTransport.assignedPhysicalActualMass_outerToSelected
#print axioms Kakeya.Streamlined.GenealogyTransport.assignedPhysicalActualMass_selectedToExact
#print axioms Kakeya.Streamlined.GenealogyTransport.assignedPhysicalActualMass_exactToScale
#print axioms Kakeya.Streamlined.GenealogyTransport.assignedPhysicalActualMass_outerGlobal
#print axioms Kakeya.Streamlined.GenealogyTransport.assignedPhysicalActualMass_outerRaw
#print axioms Kakeya.Streamlined.GenealogyTransport.assignedPhysicalActualMass_innerRaw
#print axioms Kakeya.Streamlined.GenealogyTransport.assigned_physical_actual_mass_scheduled_step
#print axioms Kakeya.Streamlined.GenealogyTransport.AssignedPhysicalActualMassScheduledStepPackage.nextWithAllCarriersPositive
#print axioms Kakeya.Streamlined.GenealogyTransport.AssignedPhysicalActualMassScheduledStepPackage.nextNode_allCarriersPositive
#print axioms Kakeya.Streamlined.GenealogyTransport.AssignedPhysicalActualMassScheduledStepPackage.toNext_shadings_heq
#print axioms Kakeya.Streamlined.GenealogyTransport.AssignedPhysicalActualMassScheduledStepPackage.allCarriersPositive
