import MyLeanRepo.Diagnostics.NumObjs
import MyLeanRepo.Kakeya.Streamlined.BalancedKatzTao.MainLemmaTwo.AssignedAlphaAspectOuterPreterminalRecursion

open Lean Elab Command

run_cmd MyLeanRepo.Diagnostics.reportNumObjs #[
  `Kakeya.Streamlined.GenealogyTransport.AssignedAlphaAspectOuterPreterminalRecursion.TerminalOutcome,
  `Kakeya.Streamlined.GenealogyTransport.AssignedAlphaAspectOuterPreterminalRecursion.PreparedOccurrence,
  `Kakeya.Streamlined.GenealogyTransport.AssignedAlphaAspectOuterPreterminalRecursion.canonicalOutcomeToPreparedOrContinuation,
  `Kakeya.Streamlined.GenealogyTransport.AssignedAlphaAspectOuterPreterminalRecursion.prepareCanonical,
  `Kakeya.Streamlined.GenealogyTransport.AssignedAlphaAspectOuterPreterminalRecursion.prepareAndRetest,
  `Kakeya.Streamlined.GenealogyTransport.AssignedAlphaAspectOuterPreterminalRecursion.run
]
