import MyLeanRepo.Diagnostics.NumObjs
import MyLeanRepo.Kakeya.Streamlined.MainLemmaTwo.PreterminalPhysicalBMDFCompositeBlockSelection

open Lean Elab Command

run_cmd MyLeanRepo.Diagnostics.reportNumObjs #[
  `Kakeya.Streamlined.markedBlockBoundedLabelCode_injective_on_observed,
  `Kakeya.Streamlined.markedBlockBoundedLabelVector_eq_iff_of_sameBlock,
  `Kakeya.Streamlined.markedBlockCompositeLocalLabel_eq_iff_of_sameBlock,
  `Kakeya.Streamlined.markedBlockCompositeRegisteredBin_spec,
  `Kakeya.Streamlined.marked_block_composite_local_label_auxiliary_tree_regularization,
  `Kakeya.Streamlined.MarkedBlockCompositeLocalLabelAuxiliaryTreePackage.selectedBlocks_chosenGlobalKey_eq,
  `Kakeya.Streamlined.MarkedBlockCompositeLocalLabelAuxiliaryTreePackage.selectedLeaves_globalSignature_eq,
  `Kakeya.Streamlined.MarkedBlockCompositeLocalLabelAuxiliaryTreePackage.selectedLeaves_localLabel_eq_of_sameBlock,
  `Kakeya.Streamlined.paperGridRestrictedSupportingLineHierarchy,
  `Kakeya.Streamlined.preterminal_physical_b_mdf_composite_block_selection,
  `Kakeya.Streamlined.PreterminalPhysicalBMDFCompositeBlockSelectionPackage.selectedLeaves_paperGridSignature_eq,
  `Kakeya.Streamlined.PreterminalPhysicalBMDFCompositeBlockSelectionPackage.restrictedSupportingHierarchy,
  `Kakeya.Streamlined.PreterminalPhysicalBMDFCompositeBlockSelectionPackage.exactInsertion,
  `Kakeya.Streamlined.PreterminalPhysicalBMDFCompositeBlockSelectionPackage.selectedLeaves_localParentLabel_eq,
  `Kakeya.Streamlined.PreterminalPhysicalBMDFCompositeBlockSelectionPackage.raw_whole_block_mapped_retest
]

#print axioms Kakeya.Streamlined.markedBlockBoundedLabelCode_injective_on_observed
#print axioms Kakeya.Streamlined.markedBlockBoundedLabelVector_eq_iff_of_sameBlock
#print axioms Kakeya.Streamlined.markedBlockCompositeLocalLabel_eq_iff_of_sameBlock
#print axioms Kakeya.Streamlined.markedBlockCompositeRegisteredBin_spec
#print axioms Kakeya.Streamlined.marked_block_composite_local_label_auxiliary_tree_regularization
#print axioms Kakeya.Streamlined.MarkedBlockCompositeLocalLabelAuxiliaryTreePackage.selectedBlocks_chosenGlobalKey_eq
#print axioms Kakeya.Streamlined.MarkedBlockCompositeLocalLabelAuxiliaryTreePackage.selectedLeaves_globalSignature_eq
#print axioms Kakeya.Streamlined.MarkedBlockCompositeLocalLabelAuxiliaryTreePackage.selectedLeaves_localLabel_eq_of_sameBlock
#print axioms Kakeya.Streamlined.paperGridRestrictedSupportingLineHierarchy
#print axioms Kakeya.Streamlined.preterminal_physical_b_mdf_composite_block_selection
#print axioms Kakeya.Streamlined.PreterminalPhysicalBMDFCompositeBlockSelectionPackage.selectedLeaves_paperGridSignature_eq
#print axioms Kakeya.Streamlined.PreterminalPhysicalBMDFCompositeBlockSelectionPackage.restrictedSupportingHierarchy
#print axioms Kakeya.Streamlined.PreterminalPhysicalBMDFCompositeBlockSelectionPackage.exactInsertion
#print axioms Kakeya.Streamlined.PreterminalPhysicalBMDFCompositeBlockSelectionPackage.selectedLeaves_localParentLabel_eq
#print axioms Kakeya.Streamlined.PreterminalPhysicalBMDFCompositeBlockSelectionPackage.raw_whole_block_mapped_retest
