import MyLeanRepo.Diagnostics.NumObjs
import MyLeanRepo.Kakeya.Streamlined.MainLemmaTwo.PreterminalPhysicalBMDFInsertedJointProfileSelection

open Lean Elab Command

run_cmd MyLeanRepo.Diagnostics.reportNumObjs #[
  `Kakeya.Streamlined.preterminalPhysicalBMDFJointMappedProfile_bounds,
  `Kakeya.Streamlined.preterminalPhysicalBMDFInsertedJointProfileBin_spec,
  `Kakeya.Streamlined.preterminalPhysicalBMDFInsertedJointRegisteredBin_spec,
  `Kakeya.Streamlined.preterminal_physical_b_mdf_inserted_joint_profile_selection,
  `Kakeya.Streamlined.PreterminalPhysicalBMDFInsertedJointSelectionPackage.selectedBlocks_chosenInternal_eq,
  `Kakeya.Streamlined.PreterminalPhysicalBMDFInsertedJointSelectionPackage.selectedLeaves_internalLabel_eq,
  `Kakeya.Streamlined.PreterminalPhysicalBMDFInsertedJointSelectionPackage.selectedLeaves_filter_physicalParent_eq_processing,
  `Kakeya.Streamlined.PreterminalPhysicalBMDFInsertedJointSelectionPackage.finalRelation_image_eq_physicalProcessing,
  `Kakeya.Streamlined.PreterminalPhysicalBMDFInsertedJointSelectionPackage.finalMappedProfile_eq_physicalProcessing,
  `Kakeya.Streamlined.PreterminalPhysicalBMDFInsertedJointSelectionPackage.finalMappedProfilesComparable,
  `Kakeya.Streamlined.PreterminalPhysicalBMDFInsertedJointSelectionPackage.vnsMappedQueryLedger,
  `Kakeya.Streamlined.PreterminalPhysicalBMDFInsertedJointSelectionPackage.raw_whole_block_mapped_retest
]

#print axioms Kakeya.Streamlined.preterminal_physical_b_mdf_inserted_joint_profile_selection
#print axioms Kakeya.Streamlined.PreterminalPhysicalBMDFInsertedJointSelectionPackage.selectedBlocks_chosenInternal_eq
#print axioms Kakeya.Streamlined.PreterminalPhysicalBMDFInsertedJointSelectionPackage.selectedLeaves_internalLabel_eq
#print axioms Kakeya.Streamlined.PreterminalPhysicalBMDFInsertedJointSelectionPackage.finalRelation_image_eq_physicalProcessing
#print axioms Kakeya.Streamlined.PreterminalPhysicalBMDFInsertedJointSelectionPackage.finalMappedProfile_eq_physicalProcessing
#print axioms Kakeya.Streamlined.PreterminalPhysicalBMDFInsertedJointSelectionPackage.vnsMappedQueryLedger
#print axioms Kakeya.Streamlined.PreterminalPhysicalBMDFInsertedJointSelectionPackage.raw_whole_block_mapped_retest
