import MyLeanRepo.Diagnostics.NumObjs
import MyLeanRepo.Kakeya.Streamlined.MainLemmaTwo.PreterminalPhysicalBMDFRawWholeBlockMappedRetest

open Lean Elab Command

run_cmd MyLeanRepo.Diagnostics.reportNumObjs #[
  `Kakeya.Streamlined.RawExactSplitCandidate.toPreterminalPhysicalBExactSplitCandidate,
  `Kakeya.Streamlined.raw_whole_block_mapped_retest,
  `Kakeya.Streamlined.raw_whole_block_mapped_retest_branch,
  `Kakeya.Streamlined.PreterminalPhysicalBMDFDynamicMappedSelectionPackage.raw_whole_block_mapped_retest
]

#print axioms Kakeya.Streamlined.RawExactSplitCandidate.toPreterminalPhysicalBExactSplitCandidate
#print axioms Kakeya.Streamlined.raw_whole_block_mapped_retest
#print axioms Kakeya.Streamlined.PreterminalPhysicalBMDFDynamicMappedSelectionPackage.raw_whole_block_mapped_retest
